"""Add invite_token to Group model

Revision ID: 3f6791eb21fd
Revises: dd99d4aa6ce1
Create Date: 2025-11-20 20:03:05.453406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6791eb21fd'
down_revision = 'dd99d4aa6ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_group_invite_token', ['invite_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('uq_group_invite_token', type_='unique')
        batch_op.drop_column('invite_token')

    # ### end Alembic commands ###
