"""Initial migration

Revision ID: 784fcc212039
Revises: 
Create Date: 2025-11-20 18:09:53.339231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784fcc212039'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tags')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('invited_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_unique_constraint('unique_group_invitation', ['group_id', 'invited_user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('oauth_provider', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint('unique_group_invitation', type_='unique')
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('invited_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
