"""Remove Budget model

Revision ID: a1b2c3d4e5f6
Revises: fbea866963d2
Create Date: 2025-11-21 16:52:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'fbea866963d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('category', sa.VARCHAR(length=100), nullable=False),
        sa.Column('amount', sa.FLOAT(), nullable=False),
        sa.Column('month', sa.INTEGER(), nullable=False),
        sa.Column('year', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###