"""Add email and first_name fields to User model

Revision ID: e94bc2248dc2
Revises: 784fcc212039
Create Date: 2025-11-20 18:30:40.197585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94bc2248dc2'
down_revision = '784fcc212039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('unique_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
