"""Add premium plan fields to User model

Revision ID: fbea866963d2
Revises: e94bc2248dc2
Create Date: 2025-11-20 19:20:27.567693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbea866963d2'
down_revision = 'e94bc2248dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('trial_start_date')
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
